### ISSUE TITLE
Researching and Reporting Nice Github Repositories

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#11]
Each team member should discover some repositories that they like and add them to the [Repository Research page](https://github.com/bounswe/bounswe2022group7/wiki/Repository-Research) that will be added to the Wiki sidebar.

**Comment by canatakan** [comment]
In my opinion, some of the key components that the relevant member found intriguing about the repository should also be included in order to provide the viewer with the underlying reasons of why it is a "good" repository.

**Comment by CahidArda** [comment]
First two repositories are added. Format of the page is still open to discussion.

**Comment by canatakan** [comment]
Since most of us has already added their contribution to our [Repository Research Report](https://github.com/bounswe/bounswe2022group7/wiki/Repository-Research) and opened their own issues for the task (mine is [here](https://github.com/bounswe/bounswe2022group7/issues/27) for instance), it can be said that the task is completed. 

I believe people can still contribute to the research; however, the soft deadline for this task has already passed. Hence, issue can be marked as completed, and then get closed.
