### ISSUE TITLE
[Use Case Diagram] Color the use cases based on use case relations

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#116]
For the diagram to be read easier, we decided in [meeting](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%239) to color nodes in [Use Case Diagram](https://github.com/bounswe/bounswe2022group7/wiki/Use-Case-Diagram) grouping them according to their conceptual similarities.

Deadline: PS on 13-04-2022
Reviewer: @musasimsekdotdll

**Comment by demet47** [comment]
I coloured view nodes the same colour irrelevant of what action they belong.
I did the rest of the colouring taking into consideration related actions for entity classes.

**Comment by erimerkin** [comment]
The text in some colours were not readable, I changed the text colour to white on these nodes.

**Comment by demet47** [comment]
I changed the colouring behaviour and groupings, creating some composite coloured nodes for commons. I prepared a legend to comprehend the colouring mechanism.
Below is the legend:
![image](https://user-images.githubusercontent.com/64031659/163501914-516f96ee-f0c6-4f4f-a9f6-ed96eff991c7.png)

**Comment by musasimsekdotdll** [comment]
Hi @demet47, you colored Use Case Diagram but the link you gave shows UML Class Diagram. I guess it is just a mistake and have updated the issue description accordingly. Other than that, the new version of Use Case Diagram looks much more readable. Thanks for your effort. I am closing this issue since no work left for that.
