### ISSUE TITLE
[Scenario] Review and edit Scenario 3 according to given feedbacks and Requirements

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#126]
Updating Acceptance Criteria according to the updated version of the [Requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)).

Deadline: 15.04.2022 01.00

**Comment by canatakan** [comment]
Edit on Scenario 3 is completed

* Acceptance criteria are updated according to new indices in [Requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft))
* References to different report systems are removed so that only Copyright Infringement Reports are mentioned in the scenario
* 1st and 2nd action items are combined
* The action item referring to making a choice between different report types is removed

The final version of Scenario 3 can be viewed [here](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-3:-Copyright-Infringement-Report).

**Comment by canatakan** [comment]
The task was handled collaboratively, and now it is done. The issue can be closed.
