### ISSUE TITLE
[Milestone 1] Evaluation of tools used until now 

### ISSUE THREAD

**Issue by azizamankenova** [bounswe/bounswe2022group7#127]
For milestone 1, I am resposible for the part of "Evaluation of tools and processes that you have used to manage your team project".
Evalation should include:
- [x] Github
- [x] Zoom
- [x] Lucidchart
- [x] Slack
- [x] Figma
- [x] ProjectLibre

**Deadline: 15.04.2022**

**Comment by canatakan** [comment]
I think [Figma](https://www.figma.com/) should also be included. We used Figma for creating mock-ups.

**Comment by azizamankenova** [comment]
> I think [Figma](https://www.figma.com/) should also be included. We used Figma for creating mock-ups.

Yeah, of course, forgot to write it. Thanks for reminding me!

**Comment by canatakan** [comment]
Since I mostly worked on ProjectLibre, I thought it would be convenient for me to complete the evaluation of it. Therefore, it is now ready for your review. 

Also, by the completion of that part, the main task now gets ready for review. I shall review the all the other 5 parts written by you, and you can review the 6th part written by me @azizamankenova.

**Comment by canatakan** [comment]
The report was finalized and submitted. Closing the issue.
