### ISSUE TITLE
[Database] Implement Admin, and CopyrightReport models

### ISSUE THREAD

**Issue by canatakan** [bounswe/bounswe2022group7#169]
The foundation of the database structure was completed. However, the [models.py](https://github.com/bounswe/bounswe2022group7/blob/practice_app/practice-app/website/models.py) file needs additional models.

The additional models that need implementation are the `Admin`, and `CopyrightReport` models.

* Implement mentioned models
* Push the updates to the [practice_app](https://github.com/bounswe/bounswe2022group7/tree/practice_app) branch directly since the base branches are already merged

**Deadline: 14/05/2022, 23:59**
**Reviewer: @azizamankenova**

**Comment by canatakan** [comment]
* The models mentioned above are created and the updates are directly pushed to the [practice_app](https://github.com/bounswe/bounswe2022group7/tree/practice-app/database-base) branch. 
* The relevant commit can be viewed [here](https://github.com/bounswe/bounswe2022group7/commit/37e27a5027897f1287201321f1b662171a2230da).

The task is now ready for review @azizamankenova

**Comment by azizamankenova** [comment]
Thanks for your work @canatakan! It looks great, but I have a few suggestions:
- I suppose there might be no need for responsible admin, as every admin should be able to see the copyright reports. And it will be easier, since we may not know who will be responsible for which copyright report during the post request.
`   
 responsible_admin = db.Column(db.Integer, db.ForeignKey( "admin.id"), primary_key=True)`
- I think a copyright report should not have a composite primary key, and ID should be the only primary key. Relevant art item does not need to be a part of a primary key.
`
 relevant_art_item = db.Column(
        db.Integer, db.ForeignKey("art_item.id"), primary_key=True)
`

**Comment by canatakan** [comment]
Thank you for your feedback @azizamankenova.

*
  > And it will be easier, since we may not know who will be responsible for which copyright report during the post request.
   
  I thought the system could assign reports to the admins automatically. Also, won't the admins only see the reports they need to resolve? Or as you told, shall all the admins be able to see all of the copyright reports? If the latter, then yes, we can simply remove this column.

* I agree with you on your second feedback. I will delete the `primary_key=True` argument.

**Comment by azizamankenova** [comment]
> I thought the system could assign reports to the admins automatically. Also, won't the admins only see the reports they need to resolve? Or as you told, shall all the admins be able to see all of the copyright reports? If the latter, then yes, we can simply remove this column.

In fact, both options are fine. I have just suggested the latter one because I guess that case would be easier to implement for those who handle copyright reports. Whatever you decide is fine by me.

**Comment by canatakan** [comment]
The `responsible_admin` field is now removed according to your feedback. The task is now completed, closing the issue.
