### ISSUE TITLE
Preparing Questions for the Customer Meeting

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#242]
We need to prepare questions for the customer meeting. We decided that everyone can contribute to this task in [our first meeting](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%231). @CahidArda will compile the questions.

Deadline: 10/10/2022 23:59
Reviewer: @canatakan

**Comment by CahidArda** [comment]
We should probably clarify how the (image or text) annotations and bookmarks work:
- Does image annotation mean highlighting a section of the image and displaying information?
- Does text annotation simply mean hyperlinks?
- What can be bookmarked; discussion threads, art items, exhibitions, user profiles? Are bookmarked pages meant to be like a read-later list?

We should also ask whether the answers to the [customer questions in CMPE352](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report) hold this semester.

**Comment by erimerkin** [comment]
Maybe we can add a question about how the follow functionality expected to work. Should we create a way to notify the followers or curating the home page for registered users with posts from followed accounts is enough?

**Comment by canatakan** [comment]
These are good questions. I only have one thing to add: 
* During our Project Plan meeting, @guneyizol has shared a website in order to clarify how we can implement annotations. 
* An example of the utilization of annotations can be seen here: https://web.hypothes.is/blog/annotation-is-now-a-web-standard/
* Maybe we can ask about this to the our customer as well.

Apart from that, these questions are necessary to clarify the mentioned vague points. They are also described in detail, in the "Notes" column.

The task is now completed, closing the issue. If anyone has something to discuss about the questions, they can re-open the issue or they may add more questions in the issue comments.
