### ISSUE TITLE
Revision of Requirements

### ISSUE THREAD

**Issue by sabrimete** [bounswe/bounswe2022group7#243]
We need to revise the requirements of the project. This is assigned to the new comers of the group to make them more knowledgeable about the project and help them to catch up with others by answering their questions.

Revision questions are going to be prepared by @sabrimete and @askabderon by 05.10.2022 23.59

**Comment by askabderon** [comment]
Here are the comments and questions about system and non-functional requirements:

- 1.2.1.4 user level is not included in profile (1.1.10) so where is it displayed to the user itself
- 1.2.1.5 why we use geotagging instead of just marking the user attendance?
- 1.2.1.6 Why do we need user level? There is no requirement that use user level. 
- 1.2.3.1 Is the map shows all the locations together or just one event? Seems like it shows all of them together but it is included in the event section.
- 1.2.4.3.2 Options for punishment are mentioned but which case is going to be selected in which scenario? Do we need duration ban as a punishment 
- 1.2.6.1.1 how do they agree? do we need to send notification about this agreement? is there a deadline for this agreement also? if the deadline is not satisfied or they dont agree what is it going to be? why dont we use fixed deadline?
- 1.2.6.1.2 what is the punishment for the bidder?
- 1.2.8.1.1 what do you mean by interaction of online galleries? threads/attenders
- 1.2.8.1.2 interaction/interest?. attended or hosted?
- 1.2.8.1.4 should be in artistic value calculation? shouldnt it only be a part of the interaction level.
- 2.5.2 Should we create our own terms of use?
- Are threads of art items and exhibitions contained in discussion forum? Is the discussion forum a seperate page? If so why there is no explanation about it?
- We dont understand the square bracket specifications, seems like they are connected with irrelevant ones.

**Comment by CahidArda** [comment]
I will attempt to clarify the confusing items and also provide suggestions for the revision:

## Functional Requiremetns
- Physical exhibition and online galleries wording is arbitrary. We chose it to differentiate them when talking
- 1.1.1.3 and 1.1.1.4 being the same: I agree
- 1.1.1.6: I agree that the usage is not clear. We may end up merging the two in the end. I am not sure.
- 1.1.4.2: Thread was meant cover comments under an gallery/exhibition page, art item or a forum. Users 'post' a discussion post, which has a 'thread' attached. This may be unnecesarily specific wording. I don't know if we need to be this specific in our wording.
- 1.1.5.2 and 1.1.5.3: Probably they edit only theirs. Not sure about collaborator. Can be a question to the customer.
- 1.1.5.4: Galleries and Exhibitions are both events.
- 1.1.5.5.2: I think map is unnecessary. Not a requirement
- 1.1.8: Biding is required (See the project description). It will be an English auction (see the first customer meetinng)
- 1.1.9.3: Can be removed.
- 1.1.11.3: I agree. Maybe we can remove the Copyright section all together.
- 1.1.12.2: We asked these in the first customer meeting (Q4). I think answers were not clear. We can ask again. 
- 1.1.13.1, 1.1.13.3: We asked these too in the custsomer meeting. I have some idea but we should ask in the meeting again I think.
- 1.1.15: Admin user is not defined in the requirements. It was invented to manage the copyright requirement. We should ask in the meeting I think.
- About search: We are asked to develop a semantic search on the platform (see project description): `In order to make this forum convenient; text used in titles and the body of the entries can be searchable semantically.`. This is mentioned in the discussion forum section but I don't know if it only covers the forum. Should ask in the meeting.

##  Non-functional requirements

- 1.2.1.4: Was asked in the customer meeting. TA said we don't need to show it
- 1.2.1.5: Geotagging is used in the wrong manner in our requirements. We don't geotag the user location. We tag the location of the event by adding a specific HMTL element to the page. This lets the search engine know about the location of the event. Should be fixed.
- 1.2.1.6: Asked in customer meeting (Q3). Not in requirements however. I think it somehow came up in avoiding malicious activity in bidding. We should ask in customer meeting if we can remove levels.
- 1.2.3.1: I think map should be removed.
- 1.2.4.3.2: Was asked in customer meeting (Q2). We should ask the copyright punishment in the customer meeting and update. 
- 1.2.6.1.1, 1.2.6.1.2: Was asked in the customer meeting (Q8). Again, I think this was overengineered. We should ask whether we should attempt to stop malicious activity. We are not developing a business application here.
- 1.2.8.1.2: Yes. This was asked in the customer meeting too (Q5). We should still ask it again to verify it I think
- 1.2.8.1.4: See Q5 in customer meeting
- 2.5.2: not sure
- Art items and exhibitons have their own pages. Thread is simply a list of comments; either under an art item, an exhibition or discussion forum post.
- Square brackets are useless at this point. They were usefull in linking not functional and functional reqs but numbers changes and they are not linked correctly anymore. Should remove them.

## Plan

We should update the reqs according to the notes we have taken. I will also add the questions that came up to #242. Some of the notes questions to the customer or things we will implement way in the future. Below, I listed the things we can do immedietly: 

| action | reason |
| - | - | 
| remove map related requirements | not a requirement | 
| Remove all references to geotagging as 'collecting user location'. Instead, add geotagging requirement to physical events. | wrong usage of geotagging |
| remove square brackets | not usefull anymore |

**Comment by askabderon** [comment]
Seems good and sufficient to me as well.

**Comment by sabrimete** [comment]
It seems that necessary actions have been taken according to @CahidArda's explanation. I am closing the issue.
