### ISSUE TITLE
Review and Update Discussion Forum Sequence Diagram

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#245]
Last year we distributed sequence diagrams among team members for them to work on individually. As decided in meeting, each of us are to review and if necessary update their own work.

Mine are as follows (ticked if the diagram has been revisioned):
- [x] Post to Discussion Forum
- [x] Reply to a thread in forum

**Deadline:** 09/10/2022, 23:59
**Reviewer:** @canatakan

**Comment by demet47** [comment]
I updated the class diagram:
- After investigating the requirements about discussion forums, I saw that discussion post is used with the name "thread" in requirements, and replies to these posts are refered to as "reply".  Our class diagram seemed to indicate one more layer of discussion: forum has post and it has threads and threads have replies unlike what requirements indicate. I fixed this by evolving the aggregation relation into inheritence relation. Now, ForumPost is a child class of ReplyThread.

**Comment by demet47** [comment]
I updated the sequence diagram as below:
![Sequence diagram - 7  Discussion Forum](https://user-images.githubusercontent.com/64031659/194948790-014cb318-221a-4675-ba2d-de17d4fe1004.png)
The previous version was as follows:
![7  Discussion Forum](https://user-images.githubusercontent.com/57228345/163859938-8d09ae21-63f4-45cf-a33e-6a8fb820aeb3.png)

**Comment by canatakan** [comment]
A couple of notes for my review:
- Please update your name at the top of the diagram.
- Instead of naming the method to get the ForumPost from the database as "find()", it should be named as a regular getter function.
- `replyPost` object should not be returned to the user in both of the alternative cases, it should be returned **only if** the function call was successful. So, this return value should also be in the alt block.

Apart from those, as we are changing the relationship between DiscussionPage, DiscussionPost and Comment classes, this diagram may need to be renamed. Nevertheless, the new version of the diagram is more correct. Thank you for your work.

After the updates on the post/comment relationship, this diagram might need to get updated, closing the issue for now though.

**Comment by demet47** [comment]
- **I want to extend the discussion on setter:**
As far as I know, getters and setters are for setting and getting variable values within code. And here, I am not updating or getting a value, rather a database object from another layer of the application: database. 

- For changing the name for mine in diagram, I did a fixation and am not the founder of the diagram (we swapped diagrams with Ali Can), so I will keep it that way but thanks for letting me clarify we hadn't document we did a swap, now we have.

- I will do the fixations related to your other comments. Thanks for your feedback!
