### ISSUE TITLE
Backend Code Initialization

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#251]
In our first [backend team meeting](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%231---12-10-2022) we decided on the technologies to utilize for backend. We are to create an initial project according to those spesifications and [deploy it to AWS](https://github.com/bounswe/bounswe2022group7/issues/252) the latter not in the scope of this issue. The spesifications are as follows:
- We are using Kotlin
- We are using MYSQL database

**Deadline:** 15/10/2022 23.59
**Reviewers:** @ekremgezgen

**Comment by sabrimete** [comment]
I initialized the Kotlin backend with Spring Boot. It is in the backend branch right now.

**Comment by sabrimete** [comment]
As a demo to understand the concept and the system, I created EC2 instance and ran MySQL Server on it. However, to connect the database from our Kotlin code we need some certificates. As I understand they are required for secure ssh connection. 

Until we create APIs and make them available to the other teams, I think this issue is not an urgent one. 
Maybe we can close this issue and create new one only to connect the database with lower priority. Because Kotlin backend is initialized right now. 

What do you think about it? @askabderon @ekremgezgen @demet47

**Comment by askabderon** [comment]
Backend branch is initialized and has been used for a while. Docker part is on another issue. Hence, I am closing this issue.
