### ISSUE TITLE
Implementation of endpoints that return Events and ArtItems

### ISSUE THREAD

**Issue by sabrimete** [bounswe/bounswe2022group7#287]
According to [backend meeting notes](https://github.com/bounswe/bounswe2022group7/wiki/BACKEND-Meeting-Notes-%232-20-10-2022), @demet47  was assigned to implement endpoints that return followings: 

- [x] Events
- [x] ArtItems

**Deadline:** 24/10/2022 23.59
**Reviewer:** @sabrimete

**Comment by CahidArda** [comment]
I would like to provide what I expect to receive in the frontend from these two endpoints. Feel free to make corrections and additions.

Focus on the common way comments and other elements are formatted in events and art item. This will help us a lot in the front-end.

## Events
```json
{
    "event_title": "Super Event",
    "description": "Super Description",
    "type": "Online",
    "location": "Super Location",
    "art_items": [
        {
            "name": "Super Art 1",
            "art_id": 1
        },
        {
            "name": "Super Art 2",
            "art_id": 2
        }
    ],
    "artists": [
        {
            "name": "Mehmet",
            "user_id": 1
        },
        {
            "name": "Fatma",
            "user_id": 2
        }
    ],
    "participants": [
        {
            "name": "Ahmet",
            "user_id": 1
        },
        {
            "name": "Filiz",
            "user_id": 2
        }
    ],
    "comments": [
        {
            "author": {
                "name": "Picasso",
                "user_id": 4,
            },
            "body": "Super Comment",
            "date": "Super date"
        }
    ]
}
```
## Art Item
```json
{
    "art_item_title": "Super Event",
    "description": "Super Description",
    "auction_id": 2,
    "artist": {
        "name": "Mehmet",
        "user_id": 1
    },
    "related_events": [
        {
            "title": "Super Event",
            "id": 2
        }
    ]
    "comments": [
        {
            "author": {
                "name": "Picasso",
                "user_id": 4,
            },
            "body": "Super Comment",
            "date": "Super date"
        }
    ],
    "labels": "?"
}
```

**Comment by demet47** [comment]
> I would like to provide what I expect to receive in the frontend from these two endpoints. Feel free to make corrections and additions.
> 
> Focus on the common way comments and other elements are formatted in events and art item. This will help us a lot in the front-end.
> 
> You may not be able to provide all of these information right away. Maybe you can add whatever you can and fill the rest with mock data so we can proceed in the front and mobile.
> 
> ## Events
> ```json
> {
>     "event_title": "Super Event",
>     "description": "Super Description",
>     "type": "Online",
>     "location": "Super Location",
>     "art_items": [
>         {
>             "name": "Super Art 1",
>             "art_id": 1
>         },
>         {
>             "name": "Super Art 2",
>             "art_id": 2
>         }
>     ],
>     "artists": [
>         {
>             "level": 4,
>             "name": "Mehmet",
>             "user_id": 1
>         },
>         {
>             "level": 4,
>             "name": "Fatma",
>             "user_id": 2
>         }
>     ],
>     "participants": [
>         {
>             "level": 4,
>             "name": "Ahmet",
>             "user_id": 1
>         },
>         {
>             "level": 4,
>             "name": "Filiz",
>             "user_id": 2
>         }
>     ],
>     "comments": [
>         {
>             "author": {
>                 "level": 4,
>                 "name": "Picasso",
>                 "user_id": 4,
>             },
>             "body": "Super Comment",
>             "date": "Super date"
>         }
>     ]
> }
> ```
> 
> ## Art Item
> ```json
> {
>     "art_item_title": "Super Event",
>     "description": "Super Description",
>     "auction_id": 2,
>     "image": "https...",
>     "artist": {
>         "level": 4,
>         "name": "Mehmet",
>         "user_id": 1
>     },
>     "related_events": [
>         {
>             "title": "Super Event",
>             "id": 2
>         }
>     ]
>     "comments": [
>         {
>             "author": {
>                 "level": 4,
>                 "name": "Picasso",
>                 "user_id": 4,
>             },
>             "body": "Super Comment",
>             "date": "Super date"
>         }
>     ],
>     "labels": "?"
> }
> ```

There are some missing entity classes for this. It will require further modifications. I just pushed a working endpoint as a trial with not-much-filled mock data. I will do required modifications as soon as possible but this extends a little bit the scope of this issue.

**Comment by demet47** [comment]
There are some missing entity features for this to be applicable. It will require further modifications. I just pushed a working endpoint as a trial with not-much-filled mock data. I will do required modifications as soon as possible but this extends a little bit the scope of this issue.

**Comment by demet47** [comment]
The relevant branch can be found [here](https://github.com/bounswe/bounswe2022group7/tree/dev/homepage-demet)

**Comment by demet47** [comment]
The current version of endpoints with their response jsons are as follows:

## (1) FOR homepage/getEventsForUser
![image](https://user-images.githubusercontent.com/64031659/198387148-6d38752a-5e15-4b01-ac15-dbbefd3395d0.png)

## (2) FOR homepage/getArtItemsForUser
![image](https://user-images.githubusercontent.com/64031659/198388489-e97b528f-254d-48d6-a219-4a9e83a66e19.png)


- For now, homepage/getGenericEvents returns the same as (1) and homepage/getGenericArtItems endpoints returns the same as (2)

**Comment by demet47** [comment]
Endpoints can be found in [here](https://github.com/bounswe/bounswe2022group7/wiki/Endpoints)

**Comment by CahidArda** [comment]
I think we should add the postman screenshots to [the wiki page aswell](https://github.com/bounswe/bounswe2022group7/wiki/Endpoints). We should also probably start documenting the endpoints [like we did in practice app](https://github.com/bounswe/bounswe2022group7/tree/master/practice-app/website/api/doc) for our own sake.

There are a couple of questions I want to ask about the implementation.

### Q1: Interpreting the JSON Response

It's not clear to me how to interpret some of the fields in the response JSON:
- Q1.1: JSON has dictionaries with fields `ìd` and `artItemInfo`. What is `id`?
- Q1.2: There is an `artItem` field which is `null`. What is that meant to be?
- Q1.3: Why do labels have escape quotes `\"`? You can simply save the string without them in the database.
- Q1.4: What is the difference between label and category? There is no reference to category in requirements.

### Q2: Making Requests for a Specific User

I also couldn't understand how we will request art items or events for user `A` from the endpoints. How does the endpoint know which user I am requesting content for?

**Comment by demet47** [comment]
Answers for @CahidArda 's questions:
 - **Q1:** id is the primary key for ArtItemInfo table. Thus one can try to find an ArtItemInfo instance in DB with this. It is auto generated and assigned in backend. This field exists for all tables btw. artItemInfo is returned as a dictionary because it is a different type of object with class type ArtItemInfo which here is mathed  with class ArtItem. 
 - **Q2:** There is a one-to-one relation between an ArtItem instance and an ArtItemInfo instance. There is a way for hibernate to automatically provide the fillment of these fields but apparently we haven't h-figured that one out yet. When we do, this field will be filled with the id of the art item it is in one-to-one relation with. Not a useful info for frontend actually.
 - **Q3:** That is for a further utilization concerning backend. That field is a string field which in reality is wanted to be considered as a JSON string. By doing this, we will be able to serialize this string. And since the elements of the label field are string, I added those escape characters.
 - **Q4:** I am not sure about this, but I have a guess:
 Categories will be utilized while implementing search engine maybe. The field exists in [UML class diagram](https://github.com/bounswe/bounswe2022group7/wiki/Class-Diagram), this is the reason why we included it.

**Comment by CahidArda** [comment]
Some answers aren't clear to me.
- Q1: There is another `id` field in the dictionary under the artItemInfo dictionary, is this one the primary key of the ArtItemInfo table?
- Q2: You have written _"When we do, this field will be filled with the id of the art item it is in one-to-one relation"_. Now we have three ids for each art item. I don't understand why I receive three ids for one art item.
- Q3: I still don't understand why you provide `"labels": "{\"something\",\"something\"}"` instead of `"labels": ["something", "something"]`. I will be able to use it right away if you provide in the second format. I have to parse the first format.

**Comment by demet47** [comment]
- **Q1:** Yes, the other id is for artItemInfo. I could have extracted it from json but since it isn't a massive data, I didn't delete it from JSON. Doing so would create a little bloated code. 
- **Q2:** As I mentioned in "UPDATE" part, the third id won't exist anymore. Only the id for artItem and artItemInfo will be present. You don't have to use artItemInfo id.
- **Q3:** It is a convention for database storage concerns. I will look if I can provide this though and give an update.

**Comment by sabrimete** [comment]
I think this issue and related issues are completed. I'm closing the issue. We can create a new issue if something comes up again.
