### ISSUE TITLE
Implement Single Art Item Endpoint 

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#302]
We need to implement an endpoint that returns a single art item to the art item detail page. The art item should be requested given the id of the art item which is an art item's primary key.

**Deadline:** 28/10/2022 23.59
**Reviewer:** @demet47

**Comment by CahidArda** [comment]
I have a quick question about this issue and #301. Should we expect to receive a JSON in [the format you have described](https://github.com/bounswe/bounswe2022group7/issues/287#issuecomment-1294019147) in #287 (Only difference being receiving a single dictionary instead of a list of dictionaries)?

**Comment by askabderon** [comment]
@CahidArda  Yes I think to return the corresponding element from art items list. However, if you have any priorities about the format, I am open to discussion.

**Comment by askabderon** [comment]
<img width="862" alt="Screen Shot 2022-10-29 at 02 40 38" src="https://user-images.githubusercontent.com/60310582/198751139-9967816a-361a-4dea-a152-b750c3288542.png">
In order to be more clear, I add the screenshot of the request and response. Do not mind the labels part, it is going to be updated and convert to array.
Also, I endpoint request will be updated to /art_item/{id} as [issue 316] (https://github.com/bounswe/bounswe2022group7/issues/316) @CahidArda

**Comment by demet47** [comment]
Review on the code for the issue:
- variables in OnlineGallery entity class should be var instead of val 
- in ArtItemController, endpoint is getting id as Int type but for the entity it is defined as Long. Int should be converted to Long
