### ISSUE TITLE
Customer Meeting Presentation Preparation

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#353]
@canatakan and I will be presenting the application in the customer meeting (1.11.2022) as part of the first milestone.

We need to prepare for the meeting by preparing a plan. I suggest we plan a table with three columns: section title, main takeaways, time. This way, we will be able to keep track of important points and the time.

Deadline: 31.10.2022, 23:59
Reviewer: ?

**Comment by CahidArda** [comment]
The features we have available in the front are the following:
- Home page
- Art item page
- Sign up page
- Sign in page

As far as I know, you couldn't finish art item page but you have the event page in mobile. I think the main focus of the presentation will be on the authentication. Here is a plan I prepared:

| Section Title | Highlights | Time |
| - | - | - |
| Intro to the App | The features we will have (events, art items, auctions, discussion page, annotations, geotagging) | 1-2 minutes |
| Intro to the Scenario | Who is this person? What does he want to do? | 1-2 minutes |
| Front Showcase | See showcase section below | 4 minutes |
| Mobile Showcase | See showcase section below | 4 minutes |

### Intro to the Scenario

We had talked about a guy who is interested in learning what his girlfriend likes. [On the art item page](https://github.com/bounswe/bounswe2022group7/pull/349), we have Janett Doe and Jano Doe who are candidates for this role. If you don't have an art item page on the mobile, we can add a person on the event page to the scenario as another friend of our guy.

Our guy is interested in learning what his girlfriend likes and knows that his girlfrind likes our platform.

### Front/Mobile Showcase 

In order to find out what his girlfriend really likes, he looks into our platform. He first looks at the pages and wants to become a member. He signs up, signs in. Then he can navigate to the pages he has been to before and observe that more functionalities are offered to him (follow user or like comment buttons). We can emit the last sentence if these functionalities are not ready in mobile.

**Comment by canatakan** [comment]
The plan looks good to me. Here are my additions:

- Are we not going to have the Event Page ready in the front-end side?

- > If you don't have an art item page on the mobile, we can add a person on the event page to the scenario as another 
   friend of our guy.

  We are still working on the Art Item Page implementation in the mobile team. You can track the progress at #331. The implementation is expected to be completed before the Milestone Presentation. 

- Also, I believe we can show that an incorrect email-password combination will be rejected during the Login process. What do you think? Is that out of the scope of the Milestone Presentation?

**Comment by demet47** [comment]
A feedback from me would be if the part where you talk about features of the app are necessary. For example we don't yet have auction implemented. I think it would be better if we just mention what we have implemented, because we are presenting to the customer and they already are the one to have requested those in the first place. They only care about what is achieved.

**Comment by canatakan** [comment]
- Further discussions were made via our communication channels.
- We had an excellent presentation with a great engagement from the audience.
- In addition to @CahidArda and I, @atillaturkmen was also helpful for the presentation set up and our team actively participated in the Q&A session as well.

Since the presentation is completed and the evaluation of it will be made in the Milestone Review Report, this issue can be closed.
