### ISSUE TITLE
Writing Part 3 of Milestone Group Review

### ISSUE THREAD

**Issue by demet47** [bounswe/bounswe2022group7#370]
According to the meeting we held after the presentations to discuss about feedbacks and what to do for milestone group report, me and @canatakan is assigned to work on "evaluation of the status of deliverables and its impact on your project plan". I am to write the initial draft and @canatakan is going to finalize it.

**Deadline**: 4/11/2022 19.30
**Reviewer**: @atillaturkmen

**Comment by demet47** [comment]
My initial draft:

All deliverables except for the project plan have been finalized. They are modified in synchrone. Requirements were the first to get finalized and it created a chain reaction of modificaitons on all other deliverables. Classes are reduced from UML Class Diagram, features such as maps are removed from mock-ups on a higher level. Payments are removed. These simplifications of course reduced the workload for each feature and our project plan is mainly distributed based on features but there is no reduction of features reflected on project plan. The only change to happen on project plan will be due to our shift in our perception on how long a feature will take. We decided that it doesn’t get squezzed to last minue. For example we will move annotations closer since it requires also some understandingof the concept (even though one of us made a research on it). We wouldn’t expect any more changes unless a customer request pops up requiring modifications on deliverables.

**Comment by canatakan** [comment]
Let us examine these changes in two sections as mentioned in the task's description:
- Evaluation of the status of deliverables
- Deliverables' impact on the Project Plan

I will then divide your feedback into these two sections and elaborate them.

**Comment by canatakan** [comment]
* I examined each deliverable in detail in the first section. 
* The second section now includes the expected updates on our Project Plan.
* The final document can be found in our internal [HackMD](https://hackmd.io/) document.

Please review Section 3 in our internal Markdown document and provide your feedback @atillaturkmen. Thanks in advance!

**Comment by atillaturkmen** [comment]
I have reviewed section 3 in the document. It accurately describes statuses of our deliverables. I have corrected two typos which were:

- I have removed the unnecessary comma in the following sentence: **We followed a different implementation scheme to deliver a product that all of its parts are fully integrated with each other, for this Milestone.**
- Corrected "modificaitons" to "modifications".

Since evaluation of the status of deliverables and its impact on your project plan is completed, I am closing this issue.

You can find final version of this document in our [deliverables folder](https://github.com/bounswe/bounswe2022group7/tree/master/deliverables).
