### ISSUE TITLE
HTTP status in endpoint responses

### ISSUE THREAD

**Issue by sabrimete** [bounswe/bounswe2022group7#376]
Backend should return HTTP status correctly for its endpoints. @askabderon is assigned to update available endpoints regarding this. 

Reviewer: @sabrimete
Deadline: 08/11/2022 23.59

**Comment by askabderon** [comment]
@sabrimete I created a [PR](https://github.com/bounswe/bounswe2022group7/pull/378) for this issue. This includes art item and event not found error with HttpStatus.NOT_FOUND.
We should also return error when the endpoint does not include necessary token for the security. Because of you implement the Authorization and token-related parts, it would be better to you implement this. 
I am creating a new issue for this and we can close this issue when the new one is done as well.

**Comment by sabrimete** [comment]
I think both this issue and related issue are completed as their PRs merged. Therefore, I'm closing the issue.
