### ISSUE TITLE
Http Token Error

### ISSUE THREAD

**Issue by askabderon** [bounswe/bounswe2022group7#379]
We should return error when the endpoint does not include the user security token.
@sabrimete is assigned for this update error.
Reviewer: @askabderon 
Deadline: 08/11/2022 23.59

**Comment by CahidArda** [comment]
I think we will need to learn how to protect an endpoint either way. For instance, this will be necessary when we add create event endpoint. Requests without a token will be rejected. However you haven't specified which endpoints you are planning to apply this in this issue. Can you specify which endpoint are you planning to apply these changes to? 

If you are going to apply this to `getEventsForUser` and `getArtItemForUser` endpoints, we were planning to ask you to change these endpoints. I just wanted to let you know in advance that we will request an update to the current event and art item endpoints.

Here is the idea: We have `getEventsForUser` and `getGenericEvents` endpoints. If we have a token in the frontend, we make a request to the `getEventsForUser`, otherwise we make a request to the `getGenericEvents` endpoint. 

However, this doesn't make much sense to me. We can have a single endpoint for both and you can check whether a token exists in our response. If there is none, you can return generic events. If there is a token, then you can return events for the user of the token. Then, we can make a request to the same endpoint which will make our lives a lot easier in the frontend.

**Comment by askabderon** [comment]
@CahidArda Actually, if we can get userID from the frontend in case of getEventsForUser (and similar endpoints to this). It may be more suitable for backend. However, I think we should make an in-depth conversation about all of the endpoints, including the future ones with the whole team in the general meeting.

**Comment by CahidArda** [comment]
The problem with providing user id in the request instead oftoken is that it's not secure. Then anyone can find a user on the platform, navigate to their profile page and learn their id, make a request to any endpoint with the user id they found and act as someone else.

As far as I know, the tokens we generate in the sign-in endpoint are created with a secret key. You should be able to decode the tokens and access it's payload. The payload should be added to the token while generating it with the secret key. Here is a prototype flow:
- User signs in and receives a token (which contains the user id as payload) created with the secret key. No one can read or create the same token since only the backend knows the secret key. Token possibly has timestamp as payload. This is probably handled by the package you are using for tokens.
- User provides the token when making a request that requires authentication. Backend decodes the token and reads the payload, user id. Backend generates the response according to the user id.

**Comment by sabrimete** [comment]
> The problem with providing user id in the request instead oftoken is that it's not secure. Then anyone can find a user on the platform, navigate to their profile page and learn their id, make a request to any endpoint with the user id they found and act as someone else.
> 
> As far as I know, the tokens we generate in the sign-in endpoint are created with a secret key. You should be able to decode the tokens and access it's payload. The payload should be added to the token while generating it with the secret key. Here is a prototype flow:
> 
> * User signs in and receives a token (which contains the user id as payload) created with the secret key. No one can read or create the same token since only the backend knows the secret key. Token possibly has timestamp as payload. This is probably handled by the package you are using for tokens.
> * User provides the token when making a request that requires authentication. Backend decodes the token and reads the payload, user id. Backend generates the response according to the user id.
> 
> We had implemented a [similar thing for our practice app](https://github.com/bounswe/bounswe2022group7/blob/master/practice-app/website/auth.py). We generated the token with `create_access_token` and it contained user information as payload. We had [Python decorators for endpoints](https://github.com/bounswe/bounswe2022group7/blob/master/practice-app/website/api/jwt.py) to check if a token is valid by decoding it and then checking whether the user type is correct. Then when it comes to using the user info, we used the `current_user` object provided to us by the package ([see create event for reference](https://github.com/bounswe/bounswe2022group7/blob/master/practice-app/website/api/event.py)).
> 
> TL:DR: You should probably look into adding user id as payload to the token and decoding the user id when you receive a token in a request.

We created a new issue for this. https://github.com/bounswe/bounswe2022group7/issues/393 

I think we can close this issue since related PR is merged.

**Comment by askabderon** [comment]
> > The problem with providing user id in the request instead oftoken is that it's not secure. Then anyone can find a user on the platform, navigate to their profile page and learn their id, make a request to any endpoint with the user id they found and act as someone else.
> > As far as I know, the tokens we generate in the sign-in endpoint are created with a secret key. You should be able to decode the tokens and access it's payload. The payload should be added to the token while generating it with the secret key. Here is a prototype flow:
> > 
> > * User signs in and receives a token (which contains the user id as payload) created with the secret key. No one can read or create the same token since only the backend knows the secret key. Token possibly has timestamp as payload. This is probably handled by the package you are using for tokens.
> > * User provides the token when making a request that requires authentication. Backend decodes the token and reads the payload, user id. Backend generates the response according to the user id.
> > 
> > We had implemented a [similar thing for our practice app](https://github.com/bounswe/bounswe2022group7/blob/master/practice-app/website/auth.py). We generated the token with `create_access_token` and it contained user information as payload. We had [Python decorators for endpoints](https://github.com/bounswe/bounswe2022group7/blob/master/practice-app/website/api/jwt.py) to check if a token is valid by decoding it and then checking whether the user type is correct. Then when it comes to using the user info, we used the `current_user` object provided to us by the package ([see create event for reference](https://github.com/bounswe/bounswe2022group7/blob/master/practice-app/website/api/event.py)).
> > TL:DR: You should probably look into adding user id as payload to the token and decoding the user id when you receive a token in a request.
> 
> We created a new issue for this. #393
> 
> I think we can close this issue since related PR is merged.

Agree with you. Closing the issue.
