### ISSUE TITLE
Prepare the Annotations Documentation Part for Milestone 2 Report

### ISSUE THREAD

**Issue by ENESAYDOGDUOGLU** [bounswe/bounswe2022group7#510]
- [ ] Describing the status of annotations in project
- [ ] Provide our plans for implementing all functionalities associated with annotations

**Comment by canatakan** [comment]
* I created another issue containing the details about this task at #512 as this one does not provide the necessary instructions as well as the fact that it does not follow a good issue format.
* Also, as we are the one who are going to work on this, it is a better idea to track this issue ourselves.
* The assignees usually have a better understanding of the job, so the issues can be more beneficial when created by themselves as well.

Because of the reasons above, I am closing this issue and the progress can be tracked at #512.
