### ISSUE TITLE
Writing the meeting notes for Meeting #1

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#6]
A meeting report should be written [on wiki](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%231) after we hold a meeting. It should include the following:
- Date, time, duration, platform and the person responsible for taking notes
- Participants
- Agenda
- Discussions
- Action items

**Comment by canatakan** [comment]
I think it would be a good idea to make some research on what should be the components of our meeting report, and [here](https://github.com/bounswe/bounswe2022group7/issues/16) I have an issue for that. The elements listed on the first comment of this issue should be in our reports firstly, and after a research on the topic, I will also share my findings to be included in the reports.

Also, since taking notes during the meetings is a progressive task, after we complete the first report, this issue can be closed and there can be different issues specific for each meeting, if needed.

**Comment by canatakan** [comment]
I prepared a template for meeting reports and the details about it can be found [here](https://github.com/bounswe/bounswe2022group7/issues/18). Please feel free to share your feedback and edit the template as you like.

**Comment by canatakan** [comment]
Following the template, I completed the notes for Meeting #1. The notes can be found [here](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%231).

Please check your duties and the report in general, any feedback is appreciated.

**Comment by canatakan** [comment]
Meeting report is completed and can be reviewed in our Wiki page. 

From now on, we should have different issues for members writing reports for different meetings. So, this issue can be closed.
