### ISSUE TITLE
Update the Requirements Page according to the answer the customer gave for 8th Question in Customer Meeting

### ISSUE THREAD

**Issue by musasimsekdotdll** [bounswe/bounswe2022group7#63]
According to the answer given for the Q8 in the [Customer Meeting](https://github.com/bounswe/bounswe2022group7/wiki/Customer-Meeting-Report), some requirements should be checked up.

Reviewer: @canatakan

**Comment by CahidArda** [comment]
Hi @musasimsekdotdll,

I have a few question about this issue:
- Do you think we should update the title of this issue and specify the question which was worked on?
- I looked at the item 1.2.6.1 which says "System shall provide a fair deadline mechanism for the completion of the money transfer of winning offers.". I remember that our requirements are required to be testable and a "fair deadline" is hard to test and verify. Do you think getting rid of 1.2.6.1 and changeing the indexes of 1.2.6.1.1 and 1.2.6.1.2 to 1.2.6.1 and 1.2.6.2 is a good idea?

**Comment by musasimsekdotdll** [comment]
Hi @CahidArda,

- I have updated the title.
- 

> I remember that our requirements are required to be testable
I agree with you but I was trying to explain how a "fair" deadline mechanism works in 1.2.6.1.* , which are parts of deadline mechanism. If it still looks problematical, I can easily change into the format you mentioned.

**Comment by canatakan** [comment]
Hello, I reviewed your updates and here are the notes:

* I also think that there is no need for mentioning the mechanism as "fair". Simply deleted that word, and paraphrased that requirement as follows:

  > 1.2.6.1: System shall provide a deadline mechanism for the completion of the asset exchange between the artist and 
  the user who made the winning offer.

* In addition, I added these requirements since they clarify what happens when an auction concludes.

  >  1.2.6.1.2: After the completion of the exchange, the artist shall be able to mark the auction as "Sold".
      1.2.6.1.3: System shall show that the auction is now completed if it is marked as "Sold" by the artist.

Thank you for your efforts @musasimsekdotdll, and thanks @CahidArda for contributing. The review is now completed and the task can be marked as completed.

**Comment by musasimsekdotdll** [comment]
Okay then, I am closing this issue. Thank you both @canatakan @CahidArda
