### ISSUE TITLE
Adding event creation use case to the use case diagram

### ISSUE THREAD

**Issue by CahidArda** [bounswe/bounswe2022group7#73]
In the [meeting #5](https://github.com/bounswe/bounswe2022group7/wiki/Meeting-Notes-%235), I (@CahidArda) and @guneyizol volunteered to work on the use cases related to the event creation and update the Use Case Diagram accordingly. The use cases we need to add include:
- Create event
- Notify followers when the exhibition is a physical exhibition

Use cases are not limited to these two.

Deadline: 2022-04-03, 14:00

**Comment by CahidArda** [comment]
The use case diagram shall include the functionalities described in the [Scenario 2, Creating Evets](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-1:-Creating-Events).

The items from the acceptance criteria which will be covered are:
- 1.1.5.1: Artists shall be able to arrange exhibitions by themselves or collaboratively.
- 1.1.5.4: Artists shall be able to notify their followers about physical exhibitions.

**Comment by CahidArda** [comment]
While adding the items and reviewing [the event creation scenario](https://github.com/bounswe/bounswe2022group7/wiki/Scenario-1:-Creating-Events), I realized that the scenario is mainly focused on physical event creation. Creating online events are not covered. Reviewing the [requirements](https://github.com/bounswe/bounswe2022group7/wiki/Requirements-(Draft)) also showed me that we don't cover adding art items to online/offline exhibitions.

I will mention this to my team mates in the next meeting.

**Comment by guneyizol** [comment]
Since user scenarios need to be very specific in what they cover, it is not possible for a single scenario to include both an online and offline event creation. For the requirements, we can add a requirement about users being able to add the artworks they selected to the online galleries. It is not very possible to select and add artworks to the physical events since those artworks might not even be displayed on the platform or artists might choose to show additional artworks to their guests.

**Comment by CahidArda** [comment]
We finalized the use cases related to event creation while working on the Use Case Diagram as a team (#84). The end version can be seen below.

![image](https://user-images.githubusercontent.com/57228345/161448470-9d76a114-47d6-4e6b-8503-3d39e72ac8d2.png)
